# TikTok Data Analysis 
In this notebook I analyze video performace and metrics with the intentions of identifying positive attributes of successful videos in order to impliment those going forward for future data driven success

### 0. Imports

In [9]:
import pandas as pd
import numpy as np
from pathlib import Path
import sys, shutil, subprocess, time, random

### 1. Read in the Data

In [18]:
path = "../data/Content.csv"
df = pd.read_csv(path)
print("Num videos:", len(df))
df

Num videos: 15

,Time,Video title,Video link,Post time,Total likes,Total comments,Total shares,Total views
0,February 15,Comment if you can’t speak English 👍,https://www.tiktok.com/@humbletoker/video/7513...,June 7,9940,382,37646,379880
1,February 15,COMMENT IF YOU GOT A #GOODNIGHT !! Did anyone ...,https://www.tiktok.com/@humbletoker/video/7520...,June 25,9275,483,18928,276957
2,February 15,Comment to receive your goodnight ✌️,https://www.tiktok.com/@humbletoker/video/7516...,June 15,8241,1697,24082,272820
3,February 15,NaN,https://www.tiktok.com/@humbletoker/video/7517...,June 19,5882,987,12904,219564
4,February 15,Did anyone win from Super Specific? 🤔 #goodnight,https://www.tiktok.com/@humbletoker/video/7518...,June 22,4797,805,17880,211013
5,February 15,Goodnight to everyone except… Did anyone get a...,https://www.tiktok.com/@humbletoker/video/7518...,June 22,4009,201,18867,203138
6,February 15,🚨Everyone who follows me before 10k gets a spe...,https://www.tiktok.com/@humbletoker/video/7516...,June 16,3909,683,18202,190324
7,February 15,Do they still teach what a mammal is in school...,https://www.tiktok.com/@humbletoker/video/7518...,June 21,3366,255,8377,158644
8,February 15,Comment if you got a goodnight tn 😄,https://www.tiktok.com/@humbletoker/video/7517...,June 17,1431,260,6127,79493
9,February 15,Goodnight to everyone except… Comment if I owe...,https://www.tiktok.com/@humbletoker/video/7519...,June 23,908,69,4835,50998
10,February 15,Comment if you got a goodnight 😁,https://www.tiktok.com/@humbletoker/video/7513...,June 8,374,31,1440,23029
11,February 15,Comment if you got a Goodnight! ✌️,https://www.tiktok.com/@humbletoker/video/7513...,June 7,241,32,1628,20710
12,February 15,First good morning vid instead of goodnight ☀️...,https://www.tiktok.com/@humbletoker/video/7518...,June 22,327,24,1088,18692
13,February 15,Anyone know the last slide? 🤔,https://www.tiktok.com/@humbletoker/video/7517...,June 18,381,199,1228,18664
14,February 15,Did anyone get it on super specific? 😳 #goodnight,https://www.tiktok.com/@humbletoker/video/7521...,June 29,141,38,913,11717

### 2. Cleaning and Feature Engineering
Vieving the data from I notice a redundant column `Time` so I will drop that column. I also want to observe how commets per view and shares per view correlate with performace (measured in views) so I will create columns for those. I will also add in a rank (by views) columns for quickly identifying how well this video placed.

In [ ]:
# --- drop redundant column ---
if "Time" in df.columns:
    df = df.drop(columns=["Time"])
df["Video title"] = df["Video title"].fillna("")

# --- primary key: extract video_id from the TikTok URL ---
df["video_id"] = df["Video link"].astype(str).str.extract(r"/video/(\d+)")
df = df.dropna(subset=["video_id"]).copy()
df["video_id"] = df["video_id"].astype(str)
df.head()

,Video title,Video link,Post time,Total likes,Total comments,Total shares,Total views,video_id
0,Comment if you can’t speak English 👍,https://www.tiktok.com/@humbletoker/video/7513...,June 7,9940,382,37646,379880,7513079996349484319
1,COMMENT IF YOU GOT A #GOODNIGHT !! Did anyone ...,https://www.tiktok.com/@humbletoker/video/7520...,June 25,9275,483,18928,276957,7520082772107595063
2,Comment to receive your goodnight ✌️,https://www.tiktok.com/@humbletoker/video/7516...,June 15,8241,1697,24082,272820,7516369352426474798
3,NaN,https://www.tiktok.com/@humbletoker/video/7517...,June 19,5882,987,12904,219564,7517866483989417271
4,Did anyone win from Super Specific? 🤔 #goodnight,https://www.tiktok.com/@humbletoker/video/7518...,June 22,4797,805,17880,211013,7518856355789212983

In [15]:
audio_dir = Path("../data/audio")
audio_dir.mkdir(parents=True, exist_ok=True)

downloaded = skipped = failed = 0
failures = []

for _, row in df.iterrows():
    video_id = str(row["video_id"])
    url = str(row["Video link"])
    out_file = audio_dir / f"{video_id}.m4a"

    # skip if already downloaded
    if out_file.exists() and out_file.stat().st_size > 0:
        skipped += 1
        continue

    cmd = [
        "yt-dlp",
        url,
        "--no-playlist",
        "-x",
        "--audio-format", "m4a",
        "--audio-quality", "0",
        "-o", str(audio_dir / f"{video_id}.%(ext)s"),
        "--force-overwrites",
        "--no-warnings",
    ]

    try:
        print(f"Downloading audio: {video_id}")
        subprocess.run(cmd, check=True)
        downloaded += 1
    except subprocess.CalledProcessError as e:
        failed += 1
        failures.append((video_id, url, str(e)))
        print(f"FAILED: {video_id}")

    # small randomized delay to reduce rate-limits
    time.sleep(random.uniform(0.8, 2.0))

print(f"\nDone. downloaded={downloaded}, skipped={skipped}, failed={failed}")

# show a few failures (if any)
if failures:
    print("\nSample failures:")
    for f in failures[:5]:
        print(f"- {f[0]} | {f[2]}")

Downloading audio: 7513079996349484319
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7513079996349484319
[TikTok] 7513079996349484319: Downloading webpage
[info] 7513079996349484319: Downloading 1 format(s): bytevc1_1080p_306061-1
[download] Destination: ../data/audio/7513079996349484319.mp4
[download] 100% of    2.12MiB in 00:00:00 at 3.51MiB/s
[ExtractAudio] Destination: ../data/audio/7513079996349484319.m4a
Deleting original file ../data/audio/7513079996349484319.mp4 (pass -k to keep)
Downloading audio: 7520082772107595063
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7520082772107595063
[TikTok] 7520082772107595063: Downloading webpage
[info] 7520082772107595063: Downloading 1 format(s): bytevc1_1080p_266677-1
[download] Destination: ../data/audio/7520082772107595063.mp4
[download] 100% of    2.42MiB in 00:00:00 at 2.64MiB/s
[ExtractAudio] Destination: ../data/audio/7520082772107595063.m4a
Deleting original file ../data/audio/7520082772107595063.mp4 (pass -k to keep)
Downloading audio: 7516369352426474798
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7516369352426474798
[TikTok] 7516369352426474798: Downloading webpage
[info] 7516369352426474798: Downloading 1 format(s): bytevc1_1080p_295914-1
[download] Destination: ../data/audio/7516369352426474798.mp4
[download] 100% of    2.19MiB in 00:00:00 at 6.27MiB/s
[ExtractAudio] Destination: ../data/audio/7516369352426474798.m4a
Deleting original file ../data/audio/7516369352426474798.mp4 (pass -k to keep)
Downloading audio: 7517866483989417271
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7517866483989417271
[TikTok] 7517866483989417271: Downloading webpage
[info] 7517866483989417271: Downloading 1 format(s): h264_540p_348224-1
[download] Destination: ../data/audio/7517866483989417271.mp4
[download] 100% of    2.91MiB in 00:00:00 at 6.22MiB/s
[ExtractAudio] Destination: ../data/audio/7517866483989417271.m4a
Deleting original file ../data/audio/7517866483989417271.mp4 (pass -k to keep)
Downloading audio: 7518856355789212983
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7518856355789212983
[TikTok] 7518856355789212983: Downloading webpage
[info] 7518856355789212983: Downloading 1 format(s): bytevc1_1080p_284881-1
[download] Destination: ../data/audio/7518856355789212983.mp4
[download] 100% of    2.11MiB in 00:00:00 at 3.72MiB/s
[ExtractAudio] Destination: ../data/audio/7518856355789212983.m4a
Deleting original file ../data/audio/7518856355789212983.mp4 (pass -k to keep)
Downloading audio: 7518971343669447991
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7518971343669447991
[TikTok] 7518971343669447991: Downloading webpage
[info] 7518971343669447991: Downloading 1 format(s): bytevc1_1080p_279767-1
[download] Destination: ../data/audio/7518971343669447991.mp4
[download] 100% of    2.29MiB in 00:00:02 at 956.59KiB/s
[ExtractAudio] Destination: ../data/audio/7518971343669447991.m4a
Deleting original file ../data/audio/7518971343669447991.mp4 (pass -k to keep)
Downloading audio: 7516742370973519117
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7516742370973519117
[TikTok] 7516742370973519117: Downloading webpage
[info] 7516742370973519117: Downloading 1 format(s): bytevc1_1080p_251141-1
[download] Destination: ../data/audio/7516742370973519117.mp4
[download] 100% of    1.97MiB in 00:00:00 at 4.89MiB/s
[ExtractAudio] Destination: ../data/audio/7516742370973519117.m4a
Deleting original file ../data/audio/7516742370973519117.mp4 (pass -k to keep)
Downloading audio: 7518596851226922295
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7518596851226922295
[TikTok] 7518596851226922295: Downloading webpage
[info] 7518596851226922295: Downloading 1 format(s): bytevc1_1080p_238132-1
[download] Destination: ../data/audio/7518596851226922295.mp4
[download] 100% of    1.82MiB in 00:00:00 at 3.36MiB/s
[ExtractAudio] Destination: ../data/audio/7518596851226922295.m4a
Deleting original file ../data/audio/7518596851226922295.mp4 (pass -k to keep)
Downloading audio: 7517115051220700471
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7517115051220700471
[TikTok] 7517115051220700471: Downloading webpage
[info] 7517115051220700471: Downloading 1 format(s): bytevc1_1080p_285674-1
[download] Destination: ../data/audio/7517115051220700471.mp4
[download] 100% of    2.10MiB in 00:00:00 at 3.55MiB/s
[ExtractAudio] Destination: ../data/audio/7517115051220700471.m4a
Deleting original file ../data/audio/7517115051220700471.mp4 (pass -k to keep)
Downloading audio: 7519342755303230775
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7519342755303230775
[TikTok] 7519342755303230775: Downloading webpage
[info] 7519342755303230775: Downloading 1 format(s): bytevc1_1080p_237597-1
[download] Destination: ../data/audio/7519342755303230775.mp4
[download] 100% of    1.63MiB in 00:00:00 at 3.26MiB/s

ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe

FAILED: 7519342755303230775
Downloading audio: 7513759914842688814
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7513759914842688814
[TikTok] 7513759914842688814: Downloading webpage
[info] 7513759914842688814: Downloading 1 format(s): bytevc1_1080p_226094-1
[download] Destination: ../data/audio/7513759914842688814.mp4
[download] 100% of    1.58MiB in 00:00:00 at 2.46MiB/s
[ExtractAudio] Destination: ../data/audio/7513759914842688814.m4a
Deleting original file ../data/audio/7513759914842688814.mp4 (pass -k to keep)
Downloading audio: 7513387289075174702
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7513387289075174702
[TikTok] 7513387289075174702: Downloading webpage
[info] 7513387289075174702: Downloading 1 format(s): bytevc1_1080p_242404-1
[download] Destination: ../data/audio/7513387289075174702.mp4
[download] 100% of    1.62MiB in 00:00:00 at 1.78MiB/s
[ExtractAudio] Destination: ../data/audio/7513387289075174702.m4a
Deleting original file ../data/audio/7513387289075174702.mp4 (pass -k to keep)
Downloading audio: 7518722677914225933
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7518722677914225933
[TikTok] 7518722677914225933: Downloading webpage
[info] 7518722677914225933: Downloading 1 format(s): bytevc1_1080p_221001-1
[download] Destination: ../data/audio/7518722677914225933.mp4
[download] 100% of    1.66MiB in 00:00:00 at 3.24MiB/s
[ExtractAudio] Destination: ../data/audio/7518722677914225933.m4a
Deleting original file ../data/audio/7518722677914225933.mp4 (pass -k to keep)
Downloading audio: 7517490052704783629
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7517490052704783629
[TikTok] 7517490052704783629: Downloading webpage
[info] 7517490052704783629: Downloading 1 format(s): bytevc1_1080p_284797-1
[download] Destination: ../data/audio/7517490052704783629.mp4
[download] 100% of    2.12MiB in 00:00:00 at 4.04MiB/s
[ExtractAudio] Destination: ../data/audio/7517490052704783629.m4a
Deleting original file ../data/audio/7517490052704783629.mp4 (pass -k to keep)
Downloading audio: 7521564052322012471
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7521564052322012471
[TikTok] 7521564052322012471: Downloading webpage
[info] 7521564052322012471: Downloading 1 format(s): bytevc1_1080p_244608-1
[download] Destination: ../data/audio/7521564052322012471.mp4
[download] 100% of    2.18MiB in 00:00:00 at 3.58MiB/s
[ExtractAudio] Destination: ../data/audio/7521564052322012471.m4a
Deleting original file ../data/audio/7521564052322012471.mp4 (pass -k to keep)

Done. downloaded=14, skipped=0, failed=1

Sample failures:
- 7519342755303230775 | Command '['yt-dlp', 'https://www.tiktok.com/@humbletoker/video/7519342755303230775', '--no-playlist', '-x', '--audio-format', 'm4a', '--audio-quality', '0', '-o', '../data/audio/7519342755303230775.%(ext)s', '--force-overwrites', '--no-warnings']' returned non-zero exit status 1.

In [19]:
import os, json, shutil, subprocess, time, random
from pathlib import Path
import pandas as pd

# ========= CONFIG =========
profile_url = "https://www.tiktok.com/@humbletoker"
audio_dir = Path("../data/audio")

# If TikTok rate-limits or shows login walls, set this to your browser:
# e.g. "chrome", "firefox". If you don't need it, leave as None.
COOKIES_FROM_BROWSER = None  # "chrome"

# Politeness delay (helps avoid rate limits)
SLEEP_MIN, SLEEP_MAX = 0.8, 2.0

# ========= 0) Clear out current audio folder =========
audio_dir.mkdir(parents=True, exist_ok=True)
for p in audio_dir.glob("*"):
    if p.is_file():
        p.unlink()
print(f"Cleared audio folder: {audio_dir.resolve()}")

# ========= 1) Dump all video metadata from your profile =========
cmd = ["yt-dlp", "--dump-json", profile_url]
if COOKIES_FROM_BROWSER:
    cmd = ["yt-dlp", "--cookies-from-browser", COOKIES_FROM_BROWSER, "--dump-json", profile_url]

proc = subprocess.run(cmd, capture_output=True, text=True)
if proc.returncode != 0:
    print("yt-dlp failed while listing profile videos.\n--- STDERR ---")
    print(proc.stderr[:4000])
    raise RuntimeError("Profile scrape failed (see stderr above).")

rows = []
for line in proc.stdout.splitlines():
    try:
        obj = json.loads(line)
    except json.JSONDecodeError:
        continue

    # Skip playlist wrapper objects (we want individual video entries)
    if obj.get("_type") == "playlist":
        continue

    video_id = obj.get("id")
    if not video_id:
        continue

    rows.append({
        "video_id": str(video_id),
        "video_url": obj.get("webpage_url") or obj.get("original_url"),
        "title": obj.get("title"),
        "upload_date": obj.get("upload_date"),
        "view_count": obj.get("view_count"),
        "like_count": obj.get("like_count"),
        "comment_count": obj.get("comment_count"),
        "repost_count": obj.get("repost_count"),
    })

videos = pd.DataFrame(rows).dropna(subset=["video_id", "video_url"]).drop_duplicates("video_id")
print(f"Found {len(videos)} videos (unique video_id).")

# Save for later use
out_csv = Path("../data/profile_videos_counts.csv")
out_csv.parent.mkdir(parents=True, exist_ok=True)
videos.to_csv(out_csv, index=False)
print(f"Saved counts to: {out_csv.resolve()}")

display_cols = ["video_id", "view_count", "like_count", "title", "video_url"]
print(videos[display_cols].sort_values("view_count", ascending=False).head(15).to_string(index=False))

# ========= 2) Download AUDIO for every video (saved as ../data/audio/<video_id>.m4a) =========
downloaded = skipped = failed = 0
fail_list = []

for _, r in videos.iterrows():
    vid = r["video_id"]
    url = r["video_url"]
    out_file = audio_dir / f"{vid}.m4a"

    if out_file.exists() and out_file.stat().st_size > 0:
        skipped += 1
        continue

    dl_cmd = [
        "yt-dlp",
        url,
        "--no-playlist",
        "-x",
        "--audio-format", "m4a",
        "--audio-quality", "0",
        "-o", str(audio_dir / f"{vid}.%(ext)s"),
        "--force-overwrites",
        "--no-warnings",
    ]
    if COOKIES_FROM_BROWSER:
        dl_cmd = [
            "yt-dlp",
            "--cookies-from-browser", COOKIES_FROM_BROWSER,
            url,
            "--no-playlist",
            "-x",
            "--audio-format", "m4a",
            "--audio-quality", "0",
            "-o", str(audio_dir / f"{vid}.%(ext)s"),
            "--force-overwrites",
            "--no-warnings",
        ]

    try:
        print(f"Downloading audio for {vid} ...")
        subprocess.run(dl_cmd, check=True)
        downloaded += 1
    except subprocess.CalledProcessError as e:
        failed += 1
        fail_list.append((vid, url, str(e)))
        print(f"FAILED {vid}")

    time.sleep(random.uniform(SLEEP_MIN, SLEEP_MAX))

print(f"\nAudio download complete. downloaded={downloaded}, skipped={skipped}, failed={failed}")
if fail_list:
    print("\nSample failures:")
    for vid, url, err in fail_list[:5]:
        print(f"- {vid} | {err}")
        print(f"  {url}")

Cleared audio folder: /Users/Logan/Desktop/TikTok Goodnight/data/audio
Found 52 videos (unique video_id).
Saved counts to: /Users/Logan/Desktop/TikTok Goodnight/data/profile_videos_counts.csv
           video_id  view_count  like_count                                                                    title                                                     video_url
7513079996349484319      379900        9940                                     Comment if you can’t speak English 👍 https://www.tiktok.com/@humbletoker/video/7513079996349484319
7520082772107595063      277000        9275 COMMENT IF YOU GOT A #GOODNIGHT !! Did anyone get it on super specific?? https://www.tiktok.com/@humbletoker/video/7520082772107595063
7516369352426474798      272800        8241                                     Comment to receive your goodnight ✌️ https://www.tiktok.com/@humbletoker/video/7516369352426474798
7517866483989417271      219600        5882                                        TikTok video #7517866483989417271 https://www.tiktok.com/@humbletoker/video/7517866483989417271
7518856355789212983      211000        4797                        Did anyone win from Super Specific? 🤔 #goodnight  https://www.tiktok.com/@humbletoker/video/7518856355789212983
7518971343669447991      203100        4009   Goodnight to everyone except… Did anyone get a gn on super specific? 🤔 https://www.tiktok.com/@humbletoker/video/7518971343669447991
7516742370973519117      190300        3909          🚨Everyone who follows me before 10k gets a special Goodnight! 🚨 https://www.tiktok.com/@humbletoker/video/7516742370973519117
7518596851226922295      158600        3366            Do they still teach what a mammal is in schools? 🤔 #goodnight https://www.tiktok.com/@humbletoker/video/7518596851226922295
7517115051220700471       79500        1431                                      Comment if you got a goodnight tn 😄 https://www.tiktok.com/@humbletoker/video/7517115051220700471
7519342755303230775       51000         908      Goodnight to everyone except… Comment if I owe you a goodnight!! 😴  https://www.tiktok.com/@humbletoker/video/7519342755303230775
7513759914842688814       23000         374                                         Comment if you got a goodnight 😁 https://www.tiktok.com/@humbletoker/video/7513759914842688814
7513387289075174702       20700         241                                       Comment if you got a Goodnight! ✌️ https://www.tiktok.com/@humbletoker/video/7513387289075174702
7517490052704783629       18700         381                                            Anyone know the last slide? 🤔 https://www.tiktok.com/@humbletoker/video/7517490052704783629
7518722677914225933       18700         327 First good morning vid instead of goodnight ☀️☀️ Have a great day eve... https://www.tiktok.com/@humbletoker/video/7518722677914225933
7521564052322012471       11700         141                        Did anyone get it on super specific? 😳 #goodnight https://www.tiktok.com/@humbletoker/video/7521564052322012471
Downloading audio for 7594277449698004238 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7594277449698004238
[TikTok] 7594277449698004238: Downloading webpage
[info] 7594277449698004238: Downloading 1 format(s): bytevc1_1080p_284647-1
[download] Destination: ../data/audio/7594277449698004238.mp4
[download] 100% of    2.18MiB in 00:00:01 at 1.27MiB/s
[ExtractAudio] Destination: ../data/audio/7594277449698004238.m4a
Deleting original file ../data/audio/7594277449698004238.mp4 (pass -k to keep)
Downloading audio for 7593500470837087501 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7593500470837087501
[TikTok] 7593500470837087501: Downloading webpage
[info] 7593500470837087501: Downloading 1 format(s): bytevc1_1080p_321082-1
[download] Destination: ../data/audio/7593500470837087501.mp4
[download] 100% of    2.82MiB in 00:00:02 at 1.35MiB/s
[ExtractAudio] Destination: ../data/audio/7593500470837087501.m4a
Deleting original file ../data/audio/7593500470837087501.mp4 (pass -k to keep)
Downloading audio for 7592046457117625613 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7592046457117625613
[TikTok] 7592046457117625613: Downloading webpage
[info] 7592046457117625613: Downloading 1 format(s): bytevc1_1080p_336759-1
[download] Destination: ../data/audio/7592046457117625613.mp4
[download] 100% of    2.55MiB in 00:00:01 at 1.36MiB/s
[ExtractAudio] Destination: ../data/audio/7592046457117625613.m4a
Deleting original file ../data/audio/7592046457117625613.mp4 (pass -k to keep)
Downloading audio for 7542733065643232526 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7542733065643232526
[TikTok] 7542733065643232526: Downloading webpage
[info] 7542733065643232526: Downloading 1 format(s): bytevc1_1080p_301834-1
[download] Destination: ../data/audio/7542733065643232526.mp4
[download] 100% of    2.28MiB in 00:00:01 at 1.38MiB/s

ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe

FAILED 7542733065643232526
Downloading audio for 7542350925122293006 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7542350925122293006
[TikTok] 7542350925122293006: Downloading webpage
[info] 7542350925122293006: Downloading 1 format(s): bytevc1_1080p_295925-1
[download] Destination: ../data/audio/7542350925122293006.mp4
[download] 100% of    2.21MiB in 00:00:01 at 1.30MiB/s
[ExtractAudio] Destination: ../data/audio/7542350925122293006.m4a
Deleting original file ../data/audio/7542350925122293006.mp4 (pass -k to keep)
Downloading audio for 7541972554903309598 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7541972554903309598
[TikTok] 7541972554903309598: Downloading webpage
[info] 7541972554903309598: Downloading 1 format(s): bytevc1_1080p_256854-1
[download] Destination: ../data/audio/7541972554903309598.mp4
[download] 100% of    1.91MiB in 00:00:01 at 1.23MiB/s
[ExtractAudio] Destination: ../data/audio/7541972554903309598.m4a
Deleting original file ../data/audio/7541972554903309598.mp4 (pass -k to keep)
Downloading audio for 7536764777184496951 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7536764777184496951
[TikTok] 7536764777184496951: Downloading webpage
[info] 7536764777184496951: Downloading 1 format(s): bytevc1_1080p_225562-1
[download] Destination: ../data/audio/7536764777184496951.mp4
[download] 100% of    1.84MiB in 00:00:01 at 1.31MiB/s
FAILED 7536764777184496951

ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe

Downloading audio for 7535666289830890807 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7535666289830890807
[TikTok] 7535666289830890807: Downloading webpage
[info] 7535666289830890807: Downloading 1 format(s): bytevc1_1080p_310809-1
[download] Destination: ../data/audio/7535666289830890807.mp4
[download] 100% of    2.30MiB in 00:00:01 at 1.32MiB/s
[ExtractAudio] Destination: ../data/audio/7535666289830890807.m4a
Deleting original file ../data/audio/7535666289830890807.mp4 (pass -k to keep)
Downloading audio for 7531214869471759647 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7531214869471759647
[TikTok] 7531214869471759647: Downloading webpage
[info] 7531214869471759647: Downloading 1 format(s): bytevc1_1080p_247646-1
[download] Destination: ../data/audio/7531214869471759647.mp4
[download] 100% of    1.85MiB in 00:00:02 at 765.54KiB/s
[ExtractAudio] Destination: ../data/audio/7531214869471759647.m4a
Deleting original file ../data/audio/7531214869471759647.mp4 (pass -k to keep)
Downloading audio for 7529733595515129102 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7529733595515129102
[TikTok] 7529733595515129102: Downloading webpage
[info] 7529733595515129102: Downloading 1 format(s): bytevc1_1080p_187655-1
[download] Destination: ../data/audio/7529733595515129102.mp4
[download] 100% of    1.52MiB in 00:00:01 at 901.84KiB/s
FAILED 7529733595515129102

ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe

Downloading audio for 7529357311370939703 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7529357311370939703
[TikTok] 7529357311370939703: Downloading webpage
[info] 7529357311370939703: Downloading 1 format(s): bytevc1_1080p_194044-1
[download] Destination: ../data/audio/7529357311370939703.mp4
[download] 100% of    1.43MiB in 00:00:01 at 1.07MiB/s
[ExtractAudio] Destination: ../data/audio/7529357311370939703.m4a
Deleting original file ../data/audio/7529357311370939703.mp4 (pass -k to keep)
Downloading audio for 7528949556499844365 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7528949556499844365
[TikTok] 7528949556499844365: Downloading webpage
[info] 7528949556499844365: Downloading 1 format(s): bytevc1_1080p_307647-1
[download] Destination: ../data/audio/7528949556499844365.mp4
[download] 100% of    2.01MiB in 00:00:01 at 1.15MiB/s
FAILED 7528949556499844365

ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe

Downloading audio for 7527514089329790222 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7527514089329790222
[TikTok] 7527514089329790222: Downloading webpage
[info] 7527514089329790222: Downloading 1 format(s): bytevc1_1080p_267809-1
[download] Destination: ../data/audio/7527514089329790222.mp4
[download] 100% of    1.81MiB in 00:00:01 at 1.36MiB/s
FAILED 7527514089329790222

ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe

Downloading audio for 7527108845336792375 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7527108845336792375
[TikTok] 7527108845336792375: Downloading webpage
[info] 7527108845336792375: Downloading 1 format(s): bytevc1_1080p_221635-1
[download] Destination: ../data/audio/7527108845336792375.mp4
[download] 100% of    1.82MiB in 00:00:01 at 1.04MiB/s
FAILED 7527108845336792375

ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe

Downloading audio for 7526766564419341623 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7526766564419341623
[TikTok] 7526766564419341623: Downloading webpage
[info] 7526766564419341623: Downloading 1 format(s): bytevc1_1080p_264110-1
[download] Destination: ../data/audio/7526766564419341623.mp4
[download] 100% of    2.19MiB in 00:00:01 at 1.39MiB/s

ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe

FAILED 7526766564419341623
Downloading audio for 7526044374434729230 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7526044374434729230
[TikTok] 7526044374434729230: Downloading webpage
[info] 7526044374434729230: Downloading 1 format(s): bytevc1_1080p_344654-1
[download] Destination: ../data/audio/7526044374434729230.mp4
[download] 100% of    2.53MiB in 00:00:01 at 1.43MiB/s
[ExtractAudio] Destination: ../data/audio/7526044374434729230.m4a
Deleting original file ../data/audio/7526044374434729230.mp4 (pass -k to keep)
Downloading audio for 7525640287578787103 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7525640287578787103
[TikTok] 7525640287578787103: Downloading webpage
[info] 7525640287578787103: Downloading 1 format(s): bytevc1_1080p_508482-1
[download] Destination: ../data/audio/7525640287578787103.mp4
[download] 100% of    3.15MiB in 00:00:02 at 1.29MiB/s
FAILED 7525640287578787103

ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe

Downloading audio for 7522326178892385550 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7522326178892385550
[TikTok] 7522326178892385550: Downloading webpage
[info] 7522326178892385550: Downloading 1 format(s): bytevc1_1080p_271823-1
[download] Destination: ../data/audio/7522326178892385550.mp4
[download] 100% of    2.21MiB in 00:00:01 at 1.29MiB/s
[ExtractAudio] Destination: ../data/audio/7522326178892385550.m4a
Deleting original file ../data/audio/7522326178892385550.mp4 (pass -k to keep)
Downloading audio for 7521849117081963790 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7521849117081963790
[TikTok] 7521849117081963790: Downloading webpage
[info] 7521849117081963790: Downloading 1 format(s): bytevc1_1080p_251515-1
[download] Destination: ../data/audio/7521849117081963790.mp4
[download] 100% of    2.22MiB in 00:00:01 at 1.29MiB/s
[ExtractAudio] Destination: ../data/audio/7521849117081963790.m4a
Deleting original file ../data/audio/7521849117081963790.mp4 (pass -k to keep)
Downloading audio for 7521564052322012471 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7521564052322012471
[TikTok] 7521564052322012471: Downloading webpage
[info] 7521564052322012471: Downloading 1 format(s): bytevc1_1080p_244608-1
[download] Destination: ../data/audio/7521564052322012471.mp4
[download] 100% of    2.18MiB in 00:00:01 at 1.72MiB/s
[ExtractAudio] Destination: ../data/audio/7521564052322012471.m4a
Deleting original file ../data/audio/7521564052322012471.mp4 (pass -k to keep)
Downloading audio for 7521167251282726158 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7521167251282726158
[TikTok] 7521167251282726158: Downloading webpage
[info] 7521167251282726158: Downloading 1 format(s): bytevc1_1080p_275584-1
[download] Destination: ../data/audio/7521167251282726158.mp4
[download] 100% of    2.39MiB in 00:00:02 at 1.01MiB/s
[ExtractAudio] Destination: ../data/audio/7521167251282726158.m4a
Deleting original file ../data/audio/7521167251282726158.mp4 (pass -k to keep)
Downloading audio for 7520082772107595063 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7520082772107595063
[TikTok] 7520082772107595063: Downloading webpage
[info] 7520082772107595063: Downloading 1 format(s): bytevc1_1080p_298530-1
[download] Destination: ../data/audio/7520082772107595063.mp4
[download] 100% of    1.94MiB in 00:00:01 at 1.44MiB/s
FAILED 7520082772107595063

ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe

Downloading audio for 7519342755303230775 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7519342755303230775
[TikTok] 7519342755303230775: Downloading webpage
[info] 7519342755303230775: Downloading 1 format(s): bytevc1_1080p_267444-1
[download] Destination: ../data/audio/7519342755303230775.mp4
[download] 100% of    2.04MiB in 00:00:01 at 1.59MiB/s
[ExtractAudio] Destination: ../data/audio/7519342755303230775.m4a
Deleting original file ../data/audio/7519342755303230775.mp4 (pass -k to keep)
Downloading audio for 7519127540263357751 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7519127540263357751
[TikTok] 7519127540263357751: Downloading webpage
[info] 7519127540263357751: Downloading 1 format(s): bytevc1_1080p_272140-1
[download] Destination: ../data/audio/7519127540263357751.mp4
[download] 100% of    1.99MiB in 00:00:01 at 1.57MiB/s
[ExtractAudio] Destination: ../data/audio/7519127540263357751.m4a
Deleting original file ../data/audio/7519127540263357751.mp4 (pass -k to keep)
Downloading audio for 7518971343669447991 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7518971343669447991
[TikTok] 7518971343669447991: Downloading webpage
[info] 7518971343669447991: Downloading 1 format(s): bytevc1_1080p_279767-1
[download] Destination: ../data/audio/7518971343669447991.mp4
[download] 100% of    2.29MiB in 00:00:01 at 1.74MiB/s
[ExtractAudio] Destination: ../data/audio/7518971343669447991.m4a
Deleting original file ../data/audio/7518971343669447991.mp4 (pass -k to keep)
Downloading audio for 7518856355789212983 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7518856355789212983
[TikTok] 7518856355789212983: Downloading webpage
[info] 7518856355789212983: Downloading 1 format(s): bytevc1_1080p_284881-1
[download] Destination: ../data/audio/7518856355789212983.mp4
[download] 100% of    2.11MiB in 00:00:01 at 1.82MiB/s
[ExtractAudio] Destination: ../data/audio/7518856355789212983.m4a
Deleting original file ../data/audio/7518856355789212983.mp4 (pass -k to keep)
Downloading audio for 7518722677914225933 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7518722677914225933
[TikTok] 7518722677914225933: Downloading webpage
[info] 7518722677914225933: Downloading 1 format(s): bytevc1_1080p_221001-1
[download] Destination: ../data/audio/7518722677914225933.mp4
[download] 100% of    1.66MiB in 00:00:01 at 1.51MiB/s
[ExtractAudio] Destination: ../data/audio/7518722677914225933.m4a
Deleting original file ../data/audio/7518722677914225933.mp4 (pass -k to keep)
Downloading audio for 7518596851226922295 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7518596851226922295
[TikTok] 7518596851226922295: Downloading webpage
[info] 7518596851226922295: Downloading 1 format(s): bytevc1_1080p_203301-1
[download] Destination: ../data/audio/7518596851226922295.mp4
[download] 100% of    1.42MiB in 00:00:00 at 1.52MiB/s
FAILED 7518596851226922295

ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe

Downloading audio for 7518237738047458573 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7518237738047458573
[TikTok] 7518237738047458573: Downloading webpage
[info] 7518237738047458573: Downloading 1 format(s): bytevc1_1080p_283797-1
[download] Destination: ../data/audio/7518237738047458573.mp4
[download] 100% of    2.05MiB in 00:00:01 at 1.33MiB/s
FAILED 7518237738047458573

ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe

Downloading audio for 7517866483989417271 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7517866483989417271
[TikTok] 7517866483989417271: Downloading webpage
[info] 7517866483989417271: Downloading 1 format(s): h264_540p_348224-1
[download] Destination: ../data/audio/7517866483989417271.mp4
[download] 100% of    2.91MiB in 00:00:01 at 1.54MiB/s
[ExtractAudio] Destination: ../data/audio/7517866483989417271.m4a
Deleting original file ../data/audio/7517866483989417271.mp4 (pass -k to keep)
Downloading audio for 7517490052704783629 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7517490052704783629
[TikTok] 7517490052704783629: Downloading webpage
[info] 7517490052704783629: Downloading 1 format(s): bytevc1_1080p_284797-1
[download] Destination: ../data/audio/7517490052704783629.mp4
[download] 100% of    2.12MiB in 00:00:01 at 1.55MiB/s
[ExtractAudio] Destination: ../data/audio/7517490052704783629.m4a
Deleting original file ../data/audio/7517490052704783629.mp4 (pass -k to keep)
Downloading audio for 7517115051220700471 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7517115051220700471
[TikTok] 7517115051220700471: Downloading webpage
[info] 7517115051220700471: Downloading 1 format(s): bytevc1_1080p_216430-1
[download] Destination: ../data/audio/7517115051220700471.mp4
[download] 100% of    1.71MiB in 00:00:01 at 1.65MiB/s
FAILED 7517115051220700471

ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe

Downloading audio for 7516742370973519117 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7516742370973519117
[TikTok] 7516742370973519117: Downloading webpage
[info] 7516742370973519117: Downloading 1 format(s): bytevc1_1080p_251141-1
[download] Destination: ../data/audio/7516742370973519117.mp4
[download] 100% of    1.97MiB in 00:00:01 at 1.90MiB/s
[ExtractAudio] Destination: ../data/audio/7516742370973519117.m4a
Deleting original file ../data/audio/7516742370973519117.mp4 (pass -k to keep)
Downloading audio for 7516369352426474798 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7516369352426474798
[TikTok] 7516369352426474798: Downloading webpage
[info] 7516369352426474798: Downloading 1 format(s): bytevc1_1080p_295914-1
[download] Destination: ../data/audio/7516369352426474798.mp4
[download] 100% of    2.19MiB in 00:00:01 at 1.86MiB/s
[ExtractAudio] Destination: ../data/audio/7516369352426474798.m4a
Deleting original file ../data/audio/7516369352426474798.mp4 (pass -k to keep)
Downloading audio for 7514903961506286878 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7514903961506286878
[TikTok] 7514903961506286878: Downloading webpage
[info] 7514903961506286878: Downloading 1 format(s): bytevc1_1080p_249395-1
[download] Destination: ../data/audio/7514903961506286878.mp4
[download] 100% of    2.00MiB in 00:00:01 at 1.43MiB/s
[ExtractAudio] Destination: ../data/audio/7514903961506286878.m4a
Deleting original file ../data/audio/7514903961506286878.mp4 (pass -k to keep)
Downloading audio for 7514539097969446186 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7514539097969446186
[TikTok] 7514539097969446186: Downloading webpage
[info] 7514539097969446186: Downloading 1 format(s): bytevc1_1080p_244575-1
[download] Destination: ../data/audio/7514539097969446186.mp4
[download] 100% of    1.81MiB in 00:00:01 at 1.52MiB/s
[ExtractAudio] Destination: ../data/audio/7514539097969446186.m4a
Deleting original file ../data/audio/7514539097969446186.mp4 (pass -k to keep)
Downloading audio for 7514160603687128366 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7514160603687128366
[TikTok] 7514160603687128366: Downloading webpage
[info] 7514160603687128366: Downloading 1 format(s): bytevc1_1080p_141313-1
[download] Destination: ../data/audio/7514160603687128366.mp4
[download] 100% of    1.15MiB in 00:00:00 at 1.64MiB/s
FAILED 7514160603687128366

ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe

Downloading audio for 7513759914842688814 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7513759914842688814
[TikTok] 7513759914842688814: Downloading webpage
[info] 7513759914842688814: Downloading 1 format(s): bytevc1_1080p_226094-1
[download] Destination: ../data/audio/7513759914842688814.mp4
[download] 100% of    1.58MiB in 00:00:00 at 1.68MiB/s
[ExtractAudio] Destination: ../data/audio/7513759914842688814.m4a
Deleting original file ../data/audio/7513759914842688814.mp4 (pass -k to keep)
Downloading audio for 7513425353528921387 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7513425353528921387
[TikTok] 7513425353528921387: Downloading webpage
[info] 7513425353528921387: Downloading 1 format(s): bytevc1_1080p_220336-1
[download] Destination: ../data/audio/7513425353528921387.mp4
[download] 100% of    1.48MiB in 00:00:01 at 1.44MiB/s
[ExtractAudio] Destination: ../data/audio/7513425353528921387.m4a
Deleting original file ../data/audio/7513425353528921387.mp4 (pass -k to keep)
Downloading audio for 7513387289075174702 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7513387289075174702
[TikTok] 7513387289075174702: Downloading webpage
[info] 7513387289075174702: Downloading 1 format(s): bytevc1_1080p_242404-1
[download] Destination: ../data/audio/7513387289075174702.mp4
[download] 100% of    1.62MiB in 00:00:01 at 1.39MiB/s
[ExtractAudio] Destination: ../data/audio/7513387289075174702.m4a
Deleting original file ../data/audio/7513387289075174702.mp4 (pass -k to keep)
Downloading audio for 7513079996349484319 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7513079996349484319
[TikTok] 7513079996349484319: Downloading webpage
[info] 7513079996349484319: Downloading 1 format(s): bytevc1_1080p_306061-1
[download] Destination: ../data/audio/7513079996349484319.mp4
[download] 100% of    2.12MiB in 00:00:01 at 1.60MiB/s
[ExtractAudio] Destination: ../data/audio/7513079996349484319.m4a
Deleting original file ../data/audio/7513079996349484319.mp4 (pass -k to keep)
Downloading audio for 7512290270671670571 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7512290270671670571
[TikTok] 7512290270671670571: Downloading webpage
[info] 7512290270671670571: Downloading 1 format(s): bytevc1_1080p_268681-1
[download] Destination: ../data/audio/7512290270671670571.mp4
[download] 100% of    1.78MiB in 00:00:03 at 504.06KiB/s
[ExtractAudio] Destination: ../data/audio/7512290270671670571.m4a
Deleting original file ../data/audio/7512290270671670571.mp4 (pass -k to keep)
Downloading audio for 7511919761123478827 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7511919761123478827
[TikTok] 7511919761123478827: Downloading webpage
[info] 7511919761123478827: Downloading 1 format(s): bytevc1_720p_176088-1
[download] Destination: ../data/audio/7511919761123478827.mp4
[download] 100% of    1.07MiB in 00:00:01 at 1006.99KiB/s
[ExtractAudio] Destination: ../data/audio/7511919761123478827.m4a
Deleting original file ../data/audio/7511919761123478827.mp4 (pass -k to keep)
Downloading audio for 7511165429734427950 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7511165429734427950
[TikTok] 7511165429734427950: Downloading webpage
[info] 7511165429734427950: Downloading 1 format(s): bytevc1_720p_190452-1
[download] Destination: ../data/audio/7511165429734427950.mp4
[download] 100% of    1.15MiB in 00:00:01 at 1.12MiB/s
[ExtractAudio] Destination: ../data/audio/7511165429734427950.m4a
Deleting original file ../data/audio/7511165429734427950.mp4 (pass -k to keep)
Downloading audio for 7510840228563651886 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7510840228563651886
[TikTok] 7510840228563651886: Downloading webpage
[info] 7510840228563651886: Downloading 1 format(s): bytevc1_720p_169595-1
[download] Destination: ../data/audio/7510840228563651886.mp4
[download] 100% of    1.21MiB in 00:00:01 at 1.20MiB/s
[ExtractAudio] Destination: ../data/audio/7510840228563651886.m4a
Deleting original file ../data/audio/7510840228563651886.mp4 (pass -k to keep)
Downloading audio for 7510432081311272222 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7510432081311272222
[TikTok] 7510432081311272222: Downloading webpage
[info] 7510432081311272222: Downloading 1 format(s): bytevc1_1080p_279522-1
[download] Destination: ../data/audio/7510432081311272222.mp4
[download] 100% of    2.34MiB in 00:00:02 at 1.05MiB/s
FAILED 7510432081311272222

ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe

Downloading audio for 7510421462252293406 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7510421462252293406
[TikTok] 7510421462252293406: Downloading webpage
[info] 7510421462252293406: Downloading 1 format(s): h264_540p_404226-1
[download] Destination: ../data/audio/7510421462252293406.mp4
[download] 100% of    1.22MiB in 00:00:01 at 1.11MiB/s
[ExtractAudio] Destination: ../data/audio/7510421462252293406.m4a
Deleting original file ../data/audio/7510421462252293406.mp4 (pass -k to keep)
Downloading audio for 7510087154660314398 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7510087154660314398
[TikTok] 7510087154660314398: Downloading webpage
[info] 7510087154660314398: Downloading 1 format(s): bytevc1_720p_177495-1
[download] Destination: ../data/audio/7510087154660314398.mp4
[download] 100% of    1.14MiB in 00:00:01 at 997.12KiB/s
[ExtractAudio] Destination: ../data/audio/7510087154660314398.m4a
Deleting original file ../data/audio/7510087154660314398.mp4 (pass -k to keep)
Downloading audio for 7509719616160042286 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7509719616160042286
[TikTok] 7509719616160042286: Downloading webpage
[info] 7509719616160042286: Downloading 1 format(s): bytevc1_1080p_230329-1
[download] Destination: ../data/audio/7509719616160042286.mp4
[download] 100% of    1.78MiB in 00:00:01 at 1.31MiB/s
[ExtractAudio] Destination: ../data/audio/7509719616160042286.m4a
Deleting original file ../data/audio/7509719616160042286.mp4 (pass -k to keep)
Downloading audio for 7509317257672101166 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7509317257672101166
[TikTok] 7509317257672101166: Downloading webpage
[info] 7509317257672101166: Downloading 1 format(s): bytevc1_1080p_301303-1
[download] Destination: ../data/audio/7509317257672101166.mp4
[download] 100% of    1.61MiB in 00:00:01 at 1.51MiB/s
FAILED 7509317257672101166

ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe

Downloading audio for 7508572618233105707 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7508572618233105707
[TikTok] 7508572618233105707: Downloading webpage
[info] 7508572618233105707: Downloading 1 format(s): bytevc1_1080p_197982-1
[download] Destination: ../data/audio/7508572618233105707.mp4
[download] 100% of    1.30MiB in 00:00:01 at 1.28MiB/s
[ExtractAudio] Destination: ../data/audio/7508572618233105707.m4a
Deleting original file ../data/audio/7508572618233105707.mp4 (pass -k to keep)
Downloading audio for 7508222226462854446 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7508222226462854446
[TikTok] 7508222226462854446: Downloading webpage
[info] 7508222226462854446: Downloading 1 format(s): bytevc1_720p_174292-1
[download] Destination: ../data/audio/7508222226462854446.mp4
[download] 100% of    1.26MiB in 00:00:00 at 1.55MiB/s
[ExtractAudio] Destination: ../data/audio/7508222226462854446.m4a
Deleting original file ../data/audio/7508222226462854446.mp4 (pass -k to keep)

Audio download complete. downloaded=37, skipped=0, failed=15

Sample failures:
- 7542733065643232526 | Command '['yt-dlp', 'https://www.tiktok.com/@humbletoker/video/7542733065643232526', '--no-playlist', '-x', '--audio-format', 'm4a', '--audio-quality', '0', '-o', '../data/audio/7542733065643232526.%(ext)s', '--force-overwrites', '--no-warnings']' returned non-zero exit status 1.
  https://www.tiktok.com/@humbletoker/video/7542733065643232526
- 7536764777184496951 | Command '['yt-dlp', 'https://www.tiktok.com/@humbletoker/video/7536764777184496951', '--no-playlist', '-x', '--audio-format', 'm4a', '--audio-quality', '0', '-o', '../data/audio/7536764777184496951.%(ext)s', '--force-overwrites', '--no-warnings']' returned non-zero exit status 1.
  https://www.tiktok.com/@humbletoker/video/7536764777184496951
- 7529733595515129102 | Command '['yt-dlp', 'https://www.tiktok.com/@humbletoker/video/7529733595515129102', '--no-playlist', '-x', '--audio-format', 'm4a', '--audio-quality', '0', '-o', '../data/audio/7529733595515129102.%(ext)s', '--force-overwrites', '--no-warnings']' returned non-zero exit status 1.
  https://www.tiktok.com/@humbletoker/video/7529733595515129102
- 7528949556499844365 | Command '['yt-dlp', 'https://www.tiktok.com/@humbletoker/video/7528949556499844365', '--no-playlist', '-x', '--audio-format', 'm4a', '--audio-quality', '0', '-o', '../data/audio/7528949556499844365.%(ext)s', '--force-overwrites', '--no-warnings']' returned non-zero exit status 1.
  https://www.tiktok.com/@humbletoker/video/7528949556499844365
- 7527514089329790222 | Command '['yt-dlp', 'https://www.tiktok.com/@humbletoker/video/7527514089329790222', '--no-playlist', '-x', '--audio-format', 'm4a', '--audio-quality', '0', '-o', '../data/audio/7527514089329790222.%(ext)s', '--force-overwrites', '--no-warnings']' returned non-zero exit status 1.
  https://www.tiktok.com/@humbletoker/video/7527514089329790222

In [20]:
import subprocess, time, random
from pathlib import Path

audio_dir = Path("../data/audio")
ffmpeg_loc = "/Users/Logan/miniforge3/bin"  # contains ffmpeg + ffprobe

# retry only videos missing .m4a
missing = []
for vid in videos["video_id"].astype(str):
    if not (audio_dir / f"{vid}.m4a").exists():
        missing.append(vid)

print("Missing audio files to retry:", len(missing))

downloaded = failed = 0
for vid in missing:
    url = f"https://www.tiktok.com/@humbletoker/video/{vid}"

    cmd = [
        "yt-dlp",
        url,
        "--no-playlist",
        "--ffmpeg-location", ffmpeg_loc,   # <-- key fix
        "-x",
        "--audio-format", "m4a",
        "--audio-quality", "0",
        "-o", str(audio_dir / f"{vid}.%(ext)s"),
        "--force-overwrites",
        "--no-warnings",
    ]

    try:
        print(f"Retrying {vid} ...")
        subprocess.run(cmd, check=True)
        downloaded += 1
    except subprocess.CalledProcessError as e:
        failed += 1
        print(f"STILL FAILED {vid}: {e}")

    time.sleep(random.uniform(0.8, 2.0))

print(f"\nRetry done. downloaded={downloaded}, failed={failed}")

Missing audio files to retry: 15
Retrying 7542733065643232526 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7542733065643232526
[TikTok] 7542733065643232526: Downloading webpage
[info] 7542733065643232526: Downloading 1 format(s): bytevc1_1080p_301834-1
Deleting existing file ../data/audio/7542733065643232526.mp4
[download] Destination: ../data/audio/7542733065643232526.mp4
[download] 100% of    2.28MiB in 00:00:02 at 1.00MiB/s

ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe

STILL FAILED 7542733065643232526: Command '['yt-dlp', 'https://www.tiktok.com/@humbletoker/video/7542733065643232526', '--no-playlist', '--ffmpeg-location', '/Users/Logan/miniforge3/bin', '-x', '--audio-format', 'm4a', '--audio-quality', '0', '-o', '../data/audio/7542733065643232526.%(ext)s', '--force-overwrites', '--no-warnings']' returned non-zero exit status 1.
Retrying 7536764777184496951 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7536764777184496951
[TikTok] 7536764777184496951: Downloading webpage
[info] 7536764777184496951: Downloading 1 format(s): bytevc1_1080p_303245-1
Deleting existing file ../data/audio/7536764777184496951.mp4
[download] Destination: ../data/audio/7536764777184496951.mp4
[download] 100% of    2.23MiB in 00:00:01 at 1.57MiB/s
[ExtractAudio] Destination: ../data/audio/7536764777184496951.m4a
Deleting original file ../data/audio/7536764777184496951.mp4 (pass -k to keep)
Retrying 7529733595515129102 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7529733595515129102
[TikTok] 7529733595515129102: Downloading webpage
[info] 7529733595515129102: Downloading 1 format(s): bytevc1_1080p_187655-1
Deleting existing file ../data/audio/7529733595515129102.mp4
[download] Destination: ../data/audio/7529733595515129102.mp4
[download] 100% of    1.52MiB in 00:00:00 at 1.56MiB/s

ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe

STILL FAILED 7529733595515129102: Command '['yt-dlp', 'https://www.tiktok.com/@humbletoker/video/7529733595515129102', '--no-playlist', '--ffmpeg-location', '/Users/Logan/miniforge3/bin', '-x', '--audio-format', 'm4a', '--audio-quality', '0', '-o', '../data/audio/7529733595515129102.%(ext)s', '--force-overwrites', '--no-warnings']' returned non-zero exit status 1.
Retrying 7528949556499844365 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7528949556499844365
[TikTok] 7528949556499844365: Downloading webpage
[info] 7528949556499844365: Downloading 1 format(s): bytevc1_1080p_307647-1
Deleting existing file ../data/audio/7528949556499844365.mp4
[download] Destination: ../data/audio/7528949556499844365.mp4
[download] 100% of    2.01MiB in 00:00:01 at 1.79MiB/s
STILL FAILED 7528949556499844365: Command '['yt-dlp', 'https://www.tiktok.com/@humbletoker/video/7528949556499844365', '--no-playlist', '--ffmpeg-location', '/Users/Logan/miniforge3/bin', '-x', '--audio-format', 'm4a', '--audio-quality', '0', '-o', '../data/audio/7528949556499844365.%(ext)s', '--force-overwrites', '--no-warnings']' returned non-zero exit status 1.

ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe

Retrying 7527514089329790222 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7527514089329790222
[TikTok] 7527514089329790222: Downloading webpage
[info] 7527514089329790222: Downloading 1 format(s): bytevc1_1080p_292209-1
Deleting existing file ../data/audio/7527514089329790222.mp4
[download] Destination: ../data/audio/7527514089329790222.mp4
[download] 100% of    2.21MiB in 00:00:02 at 1.08MiB/s
[ExtractAudio] Destination: ../data/audio/7527514089329790222.m4a
Deleting original file ../data/audio/7527514089329790222.mp4 (pass -k to keep)
Retrying 7527108845336792375 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7527108845336792375
[TikTok] 7527108845336792375: Downloading webpage
[info] 7527108845336792375: Downloading 1 format(s): bytevc1_1080p_221635-1
Deleting existing file ../data/audio/7527108845336792375.mp4
[download] Destination: ../data/audio/7527108845336792375.mp4
[download] 100% of    1.82MiB in 00:00:02 at 895.76KiB/s
STILL FAILED 7527108845336792375: Command '['yt-dlp', 'https://www.tiktok.com/@humbletoker/video/7527108845336792375', '--no-playlist', '--ffmpeg-location', '/Users/Logan/miniforge3/bin', '-x', '--audio-format', 'm4a', '--audio-quality', '0', '-o', '../data/audio/7527108845336792375.%(ext)s', '--force-overwrites', '--no-warnings']' returned non-zero exit status 1.

ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe

Retrying 7526766564419341623 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7526766564419341623
[TikTok] 7526766564419341623: Downloading webpage
[info] 7526766564419341623: Downloading 1 format(s): bytevc1_1080p_347991-1
Deleting existing file ../data/audio/7526766564419341623.mp4
[download] Destination: ../data/audio/7526766564419341623.mp4
[download] 100% of    2.58MiB in 00:00:03 at 689.40KiB/s
[ExtractAudio] Destination: ../data/audio/7526766564419341623.m4a
Deleting original file ../data/audio/7526766564419341623.mp4 (pass -k to keep)
Retrying 7525640287578787103 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7525640287578787103
[TikTok] 7525640287578787103: Downloading webpage
[info] 7525640287578787103: Downloading 1 format(s): bytevc1_1080p_508482-1
Deleting existing file ../data/audio/7525640287578787103.mp4
[download] Destination: ../data/audio/7525640287578787103.mp4
[download] 100% of    3.15MiB in 00:00:01 at 1.77MiB/s
STILL FAILED 7525640287578787103: Command '['yt-dlp', 'https://www.tiktok.com/@humbletoker/video/7525640287578787103', '--no-playlist', '--ffmpeg-location', '/Users/Logan/miniforge3/bin', '-x', '--audio-format', 'm4a', '--audio-quality', '0', '-o', '../data/audio/7525640287578787103.%(ext)s', '--force-overwrites', '--no-warnings']' returned non-zero exit status 1.

ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe

Retrying 7520082772107595063 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7520082772107595063
[TikTok] 7520082772107595063: Downloading webpage
[info] 7520082772107595063: Downloading 1 format(s): bytevc1_1080p_266677-1
Deleting existing file ../data/audio/7520082772107595063.mp4
[download] Destination: ../data/audio/7520082772107595063.mp4
[download] 100% of    2.42MiB in 00:00:02 at 978.42KiB/s
[ExtractAudio] Destination: ../data/audio/7520082772107595063.m4a
Deleting original file ../data/audio/7520082772107595063.mp4 (pass -k to keep)
Retrying 7518596851226922295 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7518596851226922295
[TikTok] 7518596851226922295: Downloading webpage
[info] 7518596851226922295: Downloading 1 format(s): bytevc1_1080p_238132-1
Deleting existing file ../data/audio/7518596851226922295.mp4
[download] Destination: ../data/audio/7518596851226922295.mp4
[download] 100% of    1.82MiB in 00:00:01 at 991.97KiB/s
[ExtractAudio] Destination: ../data/audio/7518596851226922295.m4a
Deleting original file ../data/audio/7518596851226922295.mp4 (pass -k to keep)
Retrying 7518237738047458573 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7518237738047458573
[TikTok] 7518237738047458573: Downloading webpage
[info] 7518237738047458573: Downloading 1 format(s): bytevc1_1080p_283797-1
Deleting existing file ../data/audio/7518237738047458573.mp4
[download] Destination: ../data/audio/7518237738047458573.mp4
[download] 100% of    2.05MiB in 00:00:01 at 1.45MiB/s
STILL FAILED 7518237738047458573: Command '['yt-dlp', 'https://www.tiktok.com/@humbletoker/video/7518237738047458573', '--no-playlist', '--ffmpeg-location', '/Users/Logan/miniforge3/bin', '-x', '--audio-format', 'm4a', '--audio-quality', '0', '-o', '../data/audio/7518237738047458573.%(ext)s', '--force-overwrites', '--no-warnings']' returned non-zero exit status 1.

ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe

Retrying 7517115051220700471 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7517115051220700471
[TikTok] 7517115051220700471: Downloading webpage
[info] 7517115051220700471: Downloading 1 format(s): bytevc1_1080p_285674-1
Deleting existing file ../data/audio/7517115051220700471.mp4
[download] Destination: ../data/audio/7517115051220700471.mp4
[download] 100% of    2.10MiB in 00:00:01 at 1.52MiB/s
[ExtractAudio] Destination: ../data/audio/7517115051220700471.m4a
Deleting original file ../data/audio/7517115051220700471.mp4 (pass -k to keep)
Retrying 7514160603687128366 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7514160603687128366
[TikTok] 7514160603687128366: Downloading webpage
[info] 7514160603687128366: Downloading 1 format(s): bytevc1_1080p_202914-1
Deleting existing file ../data/audio/7514160603687128366.mp4
[download] Destination: ../data/audio/7514160603687128366.mp4
[download] 100% of    1.56MiB in 00:00:01 at 1.47MiB/s
[ExtractAudio] Destination: ../data/audio/7514160603687128366.m4a
Deleting original file ../data/audio/7514160603687128366.mp4 (pass -k to keep)
Retrying 7510432081311272222 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7510432081311272222
[TikTok] 7510432081311272222: Downloading webpage
[info] 7510432081311272222: Downloading 1 format(s): bytevc1_1080p_349769-1
Deleting existing file ../data/audio/7510432081311272222.mp4
[download] Destination: ../data/audio/7510432081311272222.mp4
[download] 100% of    2.75MiB in 00:00:02 at 1.36MiB/s
[ExtractAudio] Destination: ../data/audio/7510432081311272222.m4a
Deleting original file ../data/audio/7510432081311272222.mp4 (pass -k to keep)
Retrying 7509317257672101166 ...
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7509317257672101166
[TikTok] 7509317257672101166: Downloading webpage
[info] 7509317257672101166: Downloading 1 format(s): bytevc1_1080p_259319-1
Deleting existing file ../data/audio/7509317257672101166.mp4
[download] Destination: ../data/audio/7509317257672101166.mp4
[download] 100% of    2.01MiB in 00:00:01 at 1.17MiB/s
[ExtractAudio] Destination: ../data/audio/7509317257672101166.m4a
Deleting original file ../data/audio/7509317257672101166.mp4 (pass -k to keep)

Retry done. downloaded=9, failed=6

In [21]:
import subprocess
from pathlib import Path

audio_dir = Path("../data/audio")
ffmpeg = "/Users/Logan/miniforge3/bin/ffmpeg"

# find what's still missing
missing = [vid for vid in videos["video_id"].astype(str) if not (audio_dir / f"{vid}.m4a").exists()]
print("Still missing:", len(missing))
print(missing)

recovered = 0
still_failed = []

for vid in missing:
    url = f"https://www.tiktok.com/@humbletoker/video/{vid}"
    mp4_path = audio_dir / f"{vid}.mp4"
    m4a_path = audio_dir / f"{vid}.m4a"

    try:
        # 1) download mp4 only (no extraction)
        subprocess.run([
            "yt-dlp", url,
            "--no-playlist",
            "-f", "mp4",
            "-o", str(mp4_path),
            "--force-overwrites",
            "--no-warnings"
        ], check=True)

        # 2) convert mp4 -> m4a via ffmpeg (robust)
        subprocess.run([
            ffmpeg, "-y",
            "-i", str(mp4_path),
            "-vn",
            "-ac", "1",
            "-ar", "16000",
            str(m4a_path)
        ], check=True)

        # 3) clean up mp4
        if mp4_path.exists():
            mp4_path.unlink()

        recovered += 1
        print("Recovered:", vid)

    except subprocess.CalledProcessError as e:
        still_failed.append(vid)
        print("Still failed:", vid, e)

print(f"\nRecovered {recovered}/{len(missing)}. Still failed: {len(still_failed)}")
if still_failed:
    print("Still failing IDs:", still_failed)

Still missing: 6
['7542733065643232526', '7529733595515129102', '7528949556499844365', '7527108845336792375', '7525640287578787103', '7518237738047458573']
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7542733065643232526
[TikTok] 7542733065643232526: Downloading webpage
[info] 7542733065643232526: Downloading 1 format(s): bytevc1_1080p_357046-1
Deleting existing file ../data/audio/7542733065643232526.mp4
[download] Destination: ../data/audio/7542733065643232526.mp4
[download] 100% of    2.67MiB in 00:00:01 at 1.35MiB/s

ffmpeg version 8.0.1 Copyright (c) 2000-2025 the FFmpeg developers
  built with clang version 19.1.7
  configuration: --prefix=/Users/Logan/miniforge3 --cc=arm64-apple-darwin20.0.0-clang --cxx=arm64-apple-darwin20.0.0-clang++ --nm=arm64-apple-darwin20.0.0-nm --ar=arm64-apple-darwin20.0.0-ar --disable-doc --enable-openssl --enable-demuxer=dash --enable-hardcoded-tables --enable-libfreetype --enable-libharfbuzz --enable-libfontconfig --enable-libopenh264 --enable-libdav1d --enable-cross-compile --arch=arm64 --target-os=darwin --cross-prefix=arm64-apple-darwin20.0.0- --host-cc=/Users/runner/miniforge3/conda-bld/ffmpeg_1766458828561/_build_env/bin/x86_64-apple-darwin13.4.0-clang --enable-neon --disable-gnutls --enable-libvpx --enable-libass --enable-pthreads --enable-libopenvino --enable-gpl --enable-libx264 --enable-libx265 --enable-libmp3lame --enable-libaom --enable-libsvtav1 --enable-libxml2 --enable-pic --enable-shared --disable-static --enable-version3 --enable-zlib --enable-libvorbis --enable-libopus --enable-librsvg --enable-ffplay --enable-vulkan --enable-libshaderc --pkg-config=/Users/runner/miniforge3/conda-bld/ffmpeg_1766458828561/_build_env/bin/pkg-config
  libavutil      60.  8.100 / 60.  8.100
  libavcodec     62. 11.100 / 62. 11.100
  libavformat    62.  3.100 / 62.  3.100
  libavdevice    62.  1.100 / 62.  1.100
  libavfilter    11.  4.100 / 11.  4.100
  libswscale      9.  1.100 /  9.  1.100
  libswresample   6.  1.100 /  6.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '../data/audio/7542733065643232526.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    aigc_info       : {"aigc_label_type":0}
    comment         : vid:v12044gd0000d2minpvog65pdr5nri60
    vid_md5         : c112063edfb4fbac7f1812fb66cb7bd8
    encoder         : Lavf58.76.100
  Duration: 00:01:02.83, start: 0.000000, bitrate: 357 kb/s
  Stream #0:0[0x1](und): Audio: aac (HE-AACv2) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 48 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709), 1080x1920, 302 kb/s, SAR 1:1 DAR 9:16, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
Output #0, ipod, to '../data/audio/7542733065643232526.m4a':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    aigc_info       : {"aigc_label_type":0}
    comment         : vid:v12044gd0000d2minpvog65pdr5nri60
    vid_md5         : c112063edfb4fbac7f1812fb66cb7bd8
    encoder         : Lavf62.3.100
  Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, mono, fltp, 69 kb/s (default)
    Metadata:
      encoder         : Lavc62.11.100 aac
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
[out#0/ipod @ 0x14b804080] video:0KiB audio:541KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.865854%
size=     545KiB time=00:01:02.76 bitrate=  71.2kbits/s speed= 224x elapsed=0:00:00.27
[aac @ 0x14b8052c0] Qavg: 45894.750

Recovered: 7542733065643232526
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7529733595515129102
[TikTok] 7529733595515129102: Downloading webpage
[info] 7529733595515129102: Downloading 1 format(s): bytevc1_1080p_258885-1
Deleting existing file ../data/audio/7529733595515129102.mp4
[download] Destination: ../data/audio/7529733595515129102.mp4
[download] 100% of    1.91MiB in 00:00:01 at 1.36MiB/s

ffmpeg version 8.0.1 Copyright (c) 2000-2025 the FFmpeg developers
  built with clang version 19.1.7
  configuration: --prefix=/Users/Logan/miniforge3 --cc=arm64-apple-darwin20.0.0-clang --cxx=arm64-apple-darwin20.0.0-clang++ --nm=arm64-apple-darwin20.0.0-nm --ar=arm64-apple-darwin20.0.0-ar --disable-doc --enable-openssl --enable-demuxer=dash --enable-hardcoded-tables --enable-libfreetype --enable-libharfbuzz --enable-libfontconfig --enable-libopenh264 --enable-libdav1d --enable-cross-compile --arch=arm64 --target-os=darwin --cross-prefix=arm64-apple-darwin20.0.0- --host-cc=/Users/runner/miniforge3/conda-bld/ffmpeg_1766458828561/_build_env/bin/x86_64-apple-darwin13.4.0-clang --enable-neon --disable-gnutls --enable-libvpx --enable-libass --enable-pthreads --enable-libopenvino --enable-gpl --enable-libx264 --enable-libx265 --enable-libmp3lame --enable-libaom --enable-libsvtav1 --enable-libxml2 --enable-pic --enable-shared --disable-static --enable-version3 --enable-zlib --enable-libvorbis --enable-libopus --enable-librsvg --enable-ffplay --enable-vulkan --enable-libshaderc --pkg-config=/Users/runner/miniforge3/conda-bld/ffmpeg_1766458828561/_build_env/bin/pkg-config
  libavutil      60.  8.100 / 60.  8.100
  libavcodec     62. 11.100 / 62. 11.100
  libavformat    62.  3.100 / 62.  3.100
  libavdevice    62.  1.100 / 62.  1.100
  libavfilter    11.  4.100 / 11.  4.100
  libswscale      9.  1.100 /  9.  1.100
  libswresample   6.  1.100 /  6.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '../data/audio/7529733595515129102.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    aigc_info       : {"aigc_label_type":0}
    comment         : vid:v12044gd0000d1vfncnog65sfm4qa9r0
    vid_md5         : 8b7de0a8d101d51e72ec2e51d04c6506
    encoder         : Lavf58.76.100
  Duration: 00:01:01.83, start: 0.000000, bitrate: 258 kb/s
  Stream #0:0[0x1](und): Audio: aac (HE-AACv2) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 48 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709), 1080x1920, 203 kb/s, SAR 1:1 DAR 9:16, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
Output #0, ipod, to '../data/audio/7529733595515129102.m4a':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    aigc_info       : {"aigc_label_type":0}
    comment         : vid:v12044gd0000d1vfncnog65sfm4qa9r0
    vid_md5         : 8b7de0a8d101d51e72ec2e51d04c6506
    encoder         : Lavf62.3.100
  Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, mono, fltp, 69 kb/s (default)
    Metadata:
      encoder         : Lavc62.11.100 aac
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
[out#0/ipod @ 0x1600041c0] video:0KiB audio:559KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.827883%
size=     564KiB time=00:01:01.83 bitrate=  74.7kbits/s speed= 232x elapsed=0:00:00.26
[aac @ 0x160005280] Qavg: 35435.938

Recovered: 7529733595515129102
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7528949556499844365
[TikTok] 7528949556499844365: Downloading webpage
[info] 7528949556499844365: Downloading 1 format(s): bytevc1_1080p_327434-1
Deleting existing file ../data/audio/7528949556499844365.mp4
[download] Destination: ../data/audio/7528949556499844365.mp4
[download] 100% of    2.39MiB in 00:00:01 at 1.25MiB/s

ffmpeg version 8.0.1 Copyright (c) 2000-2025 the FFmpeg developers
  built with clang version 19.1.7
  configuration: --prefix=/Users/Logan/miniforge3 --cc=arm64-apple-darwin20.0.0-clang --cxx=arm64-apple-darwin20.0.0-clang++ --nm=arm64-apple-darwin20.0.0-nm --ar=arm64-apple-darwin20.0.0-ar --disable-doc --enable-openssl --enable-demuxer=dash --enable-hardcoded-tables --enable-libfreetype --enable-libharfbuzz --enable-libfontconfig --enable-libopenh264 --enable-libdav1d --enable-cross-compile --arch=arm64 --target-os=darwin --cross-prefix=arm64-apple-darwin20.0.0- --host-cc=/Users/runner/miniforge3/conda-bld/ffmpeg_1766458828561/_build_env/bin/x86_64-apple-darwin13.4.0-clang --enable-neon --disable-gnutls --enable-libvpx --enable-libass --enable-pthreads --enable-libopenvino --enable-gpl --enable-libx264 --enable-libx265 --enable-libmp3lame --enable-libaom --enable-libsvtav1 --enable-libxml2 --enable-pic --enable-shared --disable-static --enable-version3 --enable-zlib --enable-libvorbis --enable-libopus --enable-librsvg --enable-ffplay --enable-vulkan --enable-libshaderc --pkg-config=/Users/runner/miniforge3/conda-bld/ffmpeg_1766458828561/_build_env/bin/pkg-config
  libavutil      60.  8.100 / 60.  8.100
  libavcodec     62. 11.100 / 62. 11.100
  libavformat    62.  3.100 / 62.  3.100
  libavdevice    62.  1.100 / 62.  1.100
  libavfilter    11.  4.100 / 11.  4.100
  libswscale      9.  1.100 /  9.  1.100
  libswresample   6.  1.100 /  6.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '../data/audio/7528949556499844365.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    aigc_info       : {"aigc_label_type":0}
    comment         : vid:v12044gd0000d1u34b7og65tt9db2tm0
    vid_md5         : 88c0a9fb02db26fbbc25db7505f4ac0e
    encoder         : Lavf58.76.100
  Duration: 00:01:01.28, start: 0.000000, bitrate: 327 kb/s
  Stream #0:0[0x1](und): Audio: aac (HE-AACv2) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 48 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709), 1080x1920, 272 kb/s, SAR 1:1 DAR 9:16, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
Output #0, ipod, to '../data/audio/7528949556499844365.m4a':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    aigc_info       : {"aigc_label_type":0}
    comment         : vid:v12044gd0000d1u34b7og65tt9db2tm0
    vid_md5         : 88c0a9fb02db26fbbc25db7505f4ac0e
    encoder         : Lavf62.3.100
  Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, mono, fltp, 69 kb/s (default)
    Metadata:
      encoder         : Lavc62.11.100 aac
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
[out#0/ipod @ 0x137604080] video:0KiB audio:558KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.822459%
size=     563KiB time=00:01:01.27 bitrate=  75.2kbits/s speed= 269x elapsed=0:00:00.22
[aac @ 0x137605380] Qavg: 35251.434

Recovered: 7528949556499844365
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7527108845336792375
[TikTok] 7527108845336792375: Downloading webpage
[info] 7527108845336792375: Downloading 1 format(s): bytevc1_1080p_278098-1
Deleting existing file ../data/audio/7527108845336792375.mp4
[download] Destination: ../data/audio/7527108845336792375.mp4
[download] 100% of    2.25MiB in 00:00:01 at 1.37MiB/s

ffmpeg version 8.0.1 Copyright (c) 2000-2025 the FFmpeg developers
  built with clang version 19.1.7
  configuration: --prefix=/Users/Logan/miniforge3 --cc=arm64-apple-darwin20.0.0-clang --cxx=arm64-apple-darwin20.0.0-clang++ --nm=arm64-apple-darwin20.0.0-nm --ar=arm64-apple-darwin20.0.0-ar --disable-doc --enable-openssl --enable-demuxer=dash --enable-hardcoded-tables --enable-libfreetype --enable-libharfbuzz --enable-libfontconfig --enable-libopenh264 --enable-libdav1d --enable-cross-compile --arch=arm64 --target-os=darwin --cross-prefix=arm64-apple-darwin20.0.0- --host-cc=/Users/runner/miniforge3/conda-bld/ffmpeg_1766458828561/_build_env/bin/x86_64-apple-darwin13.4.0-clang --enable-neon --disable-gnutls --enable-libvpx --enable-libass --enable-pthreads --enable-libopenvino --enable-gpl --enable-libx264 --enable-libx265 --enable-libmp3lame --enable-libaom --enable-libsvtav1 --enable-libxml2 --enable-pic --enable-shared --disable-static --enable-version3 --enable-zlib --enable-libvorbis --enable-libopus --enable-librsvg --enable-ffplay --enable-vulkan --enable-libshaderc --pkg-config=/Users/runner/miniforge3/conda-bld/ffmpeg_1766458828561/_build_env/bin/pkg-config
  libavutil      60.  8.100 / 60.  8.100
  libavcodec     62. 11.100 / 62. 11.100
  libavformat    62.  3.100 / 62.  3.100
  libavdevice    62.  1.100 / 62.  1.100
  libavfilter    11.  4.100 / 11.  4.100
  libswscale      9.  1.100 /  9.  1.100
  libswresample   6.  1.100 /  6.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '../data/audio/7527108845336792375.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    aigc_info       : {"aigc_label_type":0}
    comment         : vid:v12044gd0000d1qqhvfog65houkmji00
    vid_md5         : 58ac1a24f257d1de5934f5187a0830da
    encoder         : Lavf58.76.100
  Duration: 00:01:07.90, start: 0.000000, bitrate: 278 kb/s
  Stream #0:0[0x1](und): Audio: aac (HE-AACv2) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 48 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709), 1080x1920, 223 kb/s, SAR 1:1 DAR 9:16, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
Output #0, ipod, to '../data/audio/7527108845336792375.m4a':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    aigc_info       : {"aigc_label_type":0}
    comment         : vid:v12044gd0000d1qqhvfog65houkmji00
    vid_md5         : 58ac1a24f257d1de5934f5187a0830da
    encoder         : Lavf62.3.100
  Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, mono, fltp, 69 kb/s (default)
    Metadata:
      encoder         : Lavc62.11.100 aac
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
[out#0/ipod @ 0x137204560] video:0KiB audio:598KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.834662%
size=     603KiB time=00:01:07.87 bitrate=  72.8kbits/s speed= 221x elapsed=0:00:00.30
[aac @ 0x1372055d0] Qavg: 42866.199

Recovered: 7527108845336792375
[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7525640287578787103
[TikTok] 7525640287578787103: Downloading webpage
[info] 7525640287578787103: Downloading 1 format(s): bytevc1_1080p_508482-1
Deleting existing file ../data/audio/7525640287578787103.mp4
[download] Destination: ../data/audio/7525640287578787103.mp4
[download] 100% of    3.15MiB in 00:00:03 at 814.39KiB/s
Still failed: 7525640287578787103 Command '['/Users/Logan/miniforge3/bin/ffmpeg', '-y', '-i', '../data/audio/7525640287578787103.mp4', '-vn', '-ac', '1', '-ar', '16000', '../data/audio/7525640287578787103.m4a']' returned non-zero exit status 234.

ffmpeg version 8.0.1 Copyright (c) 2000-2025 the FFmpeg developers
  built with clang version 19.1.7
  configuration: --prefix=/Users/Logan/miniforge3 --cc=arm64-apple-darwin20.0.0-clang --cxx=arm64-apple-darwin20.0.0-clang++ --nm=arm64-apple-darwin20.0.0-nm --ar=arm64-apple-darwin20.0.0-ar --disable-doc --enable-openssl --enable-demuxer=dash --enable-hardcoded-tables --enable-libfreetype --enable-libharfbuzz --enable-libfontconfig --enable-libopenh264 --enable-libdav1d --enable-cross-compile --arch=arm64 --target-os=darwin --cross-prefix=arm64-apple-darwin20.0.0- --host-cc=/Users/runner/miniforge3/conda-bld/ffmpeg_1766458828561/_build_env/bin/x86_64-apple-darwin13.4.0-clang --enable-neon --disable-gnutls --enable-libvpx --enable-libass --enable-pthreads --enable-libopenvino --enable-gpl --enable-libx264 --enable-libx265 --enable-libmp3lame --enable-libaom --enable-libsvtav1 --enable-libxml2 --enable-pic --enable-shared --disable-static --enable-version3 --enable-zlib --enable-libvorbis --enable-libopus --enable-librsvg --enable-ffplay --enable-vulkan --enable-libshaderc --pkg-config=/Users/runner/miniforge3/conda-bld/ffmpeg_1766458828561/_build_env/bin/pkg-config
  libavutil      60.  8.100 / 60.  8.100
  libavcodec     62. 11.100 / 62. 11.100
  libavformat    62.  3.100 / 62.  3.100
  libavdevice    62.  1.100 / 62.  1.100
  libavfilter    11.  4.100 / 11.  4.100
  libswscale      9.  1.100 /  9.  1.100
  libswresample   6.  1.100 /  6.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '../data/audio/7525640287578787103.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41iso5
    aigc_info       : {"aigc_label_type":0}
    comment         : vid:v15044gf0000d1o72evog65ld4tjp5p0
    vid_md5         : 373a43fb0eb2f78bf6b47a3dff2b1b5a
    encoder         : Lavf58.76.100
  Duration: 00:01:12.17, start: 0.000000, bitrate: 366 kb/s
  Stream #0:0[0x2](und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709), 1080x1920, 506 kb/s, SAR 1:1 DAR 9:16, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : Bento4 Video Handler
      vendor_id       : [0][0][0][0]
Output #0, ipod, to '../data/audio/7525640287578787103.m4a':
[out#0/ipod @ 0x11f705f20] Output file does not contain any stream
Error opening output file ../data/audio/7525640287578787103.m4a.
Error opening output files: Invalid argument

[TikTok] Extracting URL: https://www.tiktok.com/@humbletoker/video/7518237738047458573
[TikTok] 7518237738047458573: Downloading webpage
[info] 7518237738047458573: Downloading 1 format(s): bytevc1_1080p_291001-1
Deleting existing file ../data/audio/7518237738047458573.mp4
[download] Destination: ../data/audio/7518237738047458573.mp4
[download] 100% of    2.50MiB in 00:00:02 at 1.23MiB/s

ffmpeg version 8.0.1 Copyright (c) 2000-2025 the FFmpeg developers
  built with clang version 19.1.7
  configuration: --prefix=/Users/Logan/miniforge3 --cc=arm64-apple-darwin20.0.0-clang --cxx=arm64-apple-darwin20.0.0-clang++ --nm=arm64-apple-darwin20.0.0-nm --ar=arm64-apple-darwin20.0.0-ar --disable-doc --enable-openssl --enable-demuxer=dash --enable-hardcoded-tables --enable-libfreetype --enable-libharfbuzz --enable-libfontconfig --enable-libopenh264 --enable-libdav1d --enable-cross-compile --arch=arm64 --target-os=darwin --cross-prefix=arm64-apple-darwin20.0.0- --host-cc=/Users/runner/miniforge3/conda-bld/ffmpeg_1766458828561/_build_env/bin/x86_64-apple-darwin13.4.0-clang --enable-neon --disable-gnutls --enable-libvpx --enable-libass --enable-pthreads --enable-libopenvino --enable-gpl --enable-libx264 --enable-libx265 --enable-libmp3lame --enable-libaom --enable-libsvtav1 --enable-libxml2 --enable-pic --enable-shared --disable-static --enable-version3 --enable-zlib --enable-libvorbis --enable-libopus --enable-librsvg --enable-ffplay --enable-vulkan --enable-libshaderc --pkg-config=/Users/runner/miniforge3/conda-bld/ffmpeg_1766458828561/_build_env/bin/pkg-config
  libavutil      60.  8.100 / 60.  8.100
  libavcodec     62. 11.100 / 62. 11.100
  libavformat    62.  3.100 / 62.  3.100
  libavdevice    62.  1.100 / 62.  1.100
  libavfilter    11.  4.100 / 11.  4.100
  libswscale      9.  1.100 /  9.  1.100
  libswresample   6.  1.100 /  6.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '../data/audio/7518237738047458573.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    aigc_info       : {"aigc_label_type":0}
    comment         : vid:v12044gd0000d1b274vog65g0q3uqic0
    vid_md5         : 93f8a89f87f3ddf1aab2d4d531803367
    encoder         : Lavf58.76.100
  Duration: 00:01:12.00, start: 0.000000, bitrate: 291 kb/s
  Stream #0:0[0x1](und): Audio: aac (HE-AACv2) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 48 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709), 1080x1920, 236 kb/s, SAR 1:1 DAR 9:16, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
Output #0, ipod, to '../data/audio/7518237738047458573.m4a':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    aigc_info       : {"aigc_label_type":0}
    comment         : vid:v12044gd0000d1b274vog65g0q3uqic0
    vid_md5         : 93f8a89f87f3ddf1aab2d4d531803367
    encoder         : Lavf62.3.100
  Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, mono, fltp, 69 kb/s (default)
    Metadata:
      encoder         : Lavc62.11.100 aac
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]

Recovered: 7518237738047458573

Recovered 5/6. Still failed: 1
Still failing IDs: ['7525640287578787103']

[out#0/ipod @ 0x1256042c0] video:0KiB audio:640KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.819908%
size=     645KiB time=00:01:12.02 bitrate=  73.4kbits/s speed= 252x elapsed=0:00:00.28
[aac @ 0x125605460] Qavg: 34269.742