# TikTok Performance Analysis

This notebook analyzes the performance metrics of videos from the TikTok account `@humbletoker`. The primary objective is to identify key attributes of high-performing videos to inform future content strategy and drive data-driven growth.

**Note:** The data used in this analysis is limited to the top 15 performing videos, as per the data export limitations of TikTok Studio.

### 0. Imports

In [9]:
import pandas as pd
import numpy as np
from pathlib import Path
import sys, shutil, subprocess, time, random

### 1. Read in the Data

In [18]:
path = "../data/Content.csv"
df = pd.read_c_csv(path)
print("Num videos:", len(df))
df

Num videos: 15

,Time,Video title,Video link,Post time,Total likes,Total comments,Total shares,Total views
0,February 15,Comment if you can’t speak English 👍,https://www.tiktok.com/@humbletoker/video/7513...,June 7,9940,382,37646,379880
1,February 15,COMMENT IF YOU GOT A #GOODNIGHT !! Did anyone ...,https://www.tiktok.com/@humbletoker/video/7520...,June 25,9275,483,18928,276957
2,February 15,Comment to receive your goodnight ✌️,https://www.tiktok.com/@humbletoker/video/7516...,June 15,8241,1697,24082,272820
3,February 15,NaN,https://www.tiktok.com/@humbletoker/video/7517...,June 19,5882,987,12904,219564
4,February 15,Did anyone win from Super Specific? 🤔 #goodnight,https://www.tiktok.com/@humbletoker/video/7518...,June 22,4797,805,17880,211013
5,February 15,Goodnight to everyone except… Did anyone get a...,https://www.tiktok.com/@humbletoker/video/7518...,June 22,4009,201,18867,203138
6,February 15,🚨Everyone who follows me before 10k gets a spe...,https://www.tiktok.com/@humbletoker/video/7516...,June 16,3909,683,18202,190324
7,February 15,Do they still teach what a mammal is in school...,https://www.tiktok.com/@humbletoker/video/7518...,June 21,3366,255,8377,158644
8,February 15,Comment if you got a goodnight tn 😄,https://www.tiktok.com/@humbletoker/video/7517...,June 17,1431,260,6127,79493
9,February 15,Goodnight to everyone except… Comment if I owe...,https://www.tiktok.com/@humbletoker/video/7519...,June 23,908,69,4835,50998
10,February 15,Comment if you got a goodnight 😁,https://www.tiktok.com/@humbletoker/video/7513...,June 8,374,31,1440,23029
11,February 15,Comment if you got a Goodnight! ✌️,https://www.tiktok.com/@humbletoker/video/7513...,June 7,241,32,1628,20710
12,February 15,First good morning vid instead of goodnight ☀️...,https://www.tiktok.com/@humbletoker/video/7518...,June 22,327,24,1088,18692
13,February 15,Anyone know the last slide? 🤔,https://www.tiktok.com/@humbletoker/video/7517...,June 18,381,199,1228,18664
14,February 15,Did anyone get it on super specific? 😳 #goodnight,https://www.tiktok.com/@humbletoker/video/7521...,June 29,141,38,913,11717

### 2. Cleaning and Feature Engineering
Vieving the data from I notice a redundant column `Time` so I will drop that column. I also want to observe how commets per view and shares per view correlate with performace (measured in views) so I will create columns for those. I will also add in a rank (by views) columns for quickly identifying how well this video placed.

In [ ]:
# --- drop redundant column ---
if "Time" in df.columns:
    df = df.drop(columns=["Time"])
df["Video title"] = df["Video title"].fillna("")

# --- primary key: extract video_id from the TikTok URL ---
df["video_id"] = df["Video link"].astype(str).str.extract(r"/video/(\d+)")
df = df.dropna(subset=["video_id"]).copy()
df["video_id"] = df["video_id"].astype(str)
df.head()

,Video title,Video link,Post time,Total likes,Total comments,Total shares,Total views,video_id
0,Comment if you can’t speak English 👍,https://www.tiktok.com/@humbletoker/video/7513...,June 7,9940,382,37646,379880,7513079996349484319
1,COMMENT IF YOU GOT A #GOODNIGHT !! Did anyone ...,https://www.tiktok.com/@humbletoker/video/7520...,June 25,9275,483,18928,276957,7520082772107595063
2,Comment to receive your goodnight ✌️,https://www.tiktok.com/@humbletoker/video/7516...,June 15,8241,1697,24082,272820,7516369352426474798
3,NaN,https://www.tiktok.com/@humbletoker/video/7517...,June 19,5882,987,12904,219564,7517866483989417271
4,Did anyone win from Super Specific? 🤔 #goodnight,https://www.tiktok.com/@humbletoker/video/7518...,June 22,4797,805,17880,211013,7518856355789212983